// Package tunnel exposes the panel from outside the house, and routes traffic
// out through somewhere else.
//
// Both are opt-in, and the reason is the same: they hand a third party
// something. A Cloudflare Tunnel terminates TLS at Cloudflare, so the company
// can see the panel traffic; an egress profile sends the household's browsing
// to whoever runs the far end. Those are reasonable trades for some people and
// unacceptable for others, so nothing here is enabled by default and the panel
// says plainly what each option gives away.
//
// The default remains the safest one: the panel listens on the LAN and on the
// WireGuard interface, and reaching it from outside means bringing up the
// tunnel you already have.
package tunnel

import (
	"context"
	"fmt"
	"net/netip"
	"os/exec"
	"strings"
)

// CloudflareConfig describes an ingress tunnel.
type CloudflareConfig struct {
	// TunnelID and CredentialsFile come from `cloudflared tunnel create`.
	TunnelID        string
	CredentialsFile string

	// Hostname is the public name the panel answers on.
	Hostname string

	// Service is the local address cloudflared forwards to.
	Service string
}

// Validate reports what is missing.
func (c CloudflareConfig) Validate() error {
	var problems []string

	if c.TunnelID == "" {
		problems = append(problems, "a tunnel id is required")
	}
	if c.CredentialsFile == "" {
		problems = append(problems, "a credentials file is required")
	}
	if c.Hostname == "" {
		problems = append(problems, "a hostname is required")
	}
	if c.Service == "" {
		problems = append(problems, "a local service address is required")
	}

	if len(problems) > 0 {
		return fmt.Errorf("cloudflare tunnel: %s", strings.Join(problems, "; "))
	}

	return nil
}

// RenderCloudflareConfig produces a cloudflared configuration file.
func RenderCloudflareConfig(cfg CloudflareConfig) (string, error) {
	if err := cfg.Validate(); err != nil {
		return "", err
	}

	var b strings.Builder

	b.WriteString("# Generated by SedDNS. Edits will be overwritten.\n")
	b.WriteString("tunnel: " + cfg.TunnelID + "\n")
	b.WriteString("credentials-file: " + cfg.CredentialsFile + "\n")
	b.WriteString("\ningress:\n")
	b.WriteString("  - hostname: " + cfg.Hostname + "\n")
	b.WriteString("    service: " + cfg.Service + "\n")
	// A catch-all is mandatory; without it cloudflared refuses to start, and
	// leaving it open would expose whatever else is on this host.
	b.WriteString("  - service: http_status:404\n")

	return b.String(), nil
}

// CloudflaredAvailable reports whether the tunnel client is installed.
func CloudflaredAvailable() bool {
	_, err := exec.LookPath("cloudflared")

	return err == nil
}

// CloudflaredVersion returns the installed version, for the panel.
func CloudflaredVersion(ctx context.Context) (version string, err error) {
	out, err := exec.CommandContext(ctx, "cloudflared", "--version").Output()
	if err != nil {
		return "", fmt.Errorf("running cloudflared: %w", err)
	}

	return strings.TrimSpace(string(out)), nil
}

// Exposure describes how the panel can be reached, and what each way costs.
type Exposure struct {
	Method      string `json:"method"`
	Available   bool   `json:"available"`
	Recommended bool   `json:"recommended"`
	Tradeoff    string `json:"tradeoff"`
}

// Exposures lists the ways to reach the panel from outside, with what each one
// gives away.
//
// This is presented as a choice rather than a setting, because the safe option
// is not the convenient one and an operator picking blind will pick wrong.
func Exposures(wireGuardAvailable bool) []Exposure {
	return []Exposure{{
		Method:      "wireguard",
		Available:   wireGuardAvailable,
		Recommended: true,
		Tradeoff: "Nothing is exposed. You reach the panel through the tunnel you already " +
			"use for filtering, and no third party sees anything.",
	}, {
		Method:      "cloudflare-tunnel",
		Available:   CloudflaredAvailable(),
		Recommended: false,
		Tradeoff: "No inbound port and your address stays hidden, but Cloudflare terminates " +
			"TLS and can see the panel traffic. Pair it with Cloudflare Access so the login " +
			"is not the only thing standing in front of your network.",
	}, {
		Method:      "port-forward",
		Available:   true,
		Recommended: false,
		Tradeoff: "Direct and dependency-free, and it puts the panel on the public internet. " +
			"Only sensible behind a certificate and with two-factor switched on.",
	}}
}

// EgressProfile sends traffic out through somewhere else.
type EgressProfile struct {
	// Name identifies the profile in the panel.
	Name string

	// Interface is the WireGuard interface the profile brings up.
	Interface string

	// ConfigPath is a wg-quick file supplied by the provider — Mullvad, Proton,
	// or wgcf for Cloudflare WARP.
	ConfigPath string

	// Table is the routing table the profile's default route lives in, so it
	// does not become the default for the whole node.
	Table int

	// Mark selects the table for marked packets.
	Mark int

	// Sources are the clients routed through this profile.
	Sources []netip.Prefix
}

// Validate reports what is missing or would be dangerous.
func (p EgressProfile) Validate() error {
	var problems []string

	if p.Name == "" {
		problems = append(problems, "a name is required")
	}
	if p.Interface == "" {
		problems = append(problems, "an interface is required")
	}
	if p.Table <= 0 || p.Table > 252 {
		// 253-255 are the kernel's own tables; taking one would break routing
		// in a way that is very hard to diagnose.
		problems = append(problems, "table must be between 1 and 252")
	}
	if p.Mark <= 0 {
		problems = append(problems, "a firewall mark is required")
	}
	if len(p.Sources) == 0 {
		problems = append(problems, "at least one source range is required")
	}

	if len(problems) > 0 {
		return fmt.Errorf("egress profile: %s", strings.Join(problems, "; "))
	}

	return nil
}

// RenderPolicyRouting produces the rules that send selected clients out
// through the profile.
//
// The kill switch is not optional. A policy route whose interface goes down
// falls back to the ordinary default route, so the traffic the operator
// deliberately sent through a VPN would quietly leave over their own line
// instead — which is the one outcome they were trying to avoid.
func RenderPolicyRouting(p EgressProfile) (string, error) {
	if err := p.Validate(); err != nil {
		return "", err
	}

	var b strings.Builder

	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by SedDNS. Edits will be overwritten.\n")
	b.WriteString("set -e\n\n")

	fmt.Fprintf(&b, "# Route marked packets through the %s profile.\n", p.Name)
	fmt.Fprintf(&b, "ip rule add fwmark %d table %d priority 100 2>/dev/null || true\n", p.Mark, p.Table)
	fmt.Fprintf(&b, "ip route replace default dev %s table %d\n\n", p.Interface, p.Table)

	b.WriteString("# Mark the selected clients.\n")
	b.WriteString("nft -f - <<'RULES'\n")
	b.WriteString("table inet aegisdns_egress\n")
	b.WriteString("delete table inet aegisdns_egress\n")
	b.WriteString("table inet aegisdns_egress {\n")
	b.WriteString("\tchain mark {\n")
	b.WriteString("\t\ttype route hook output priority -150; policy accept;\n")
	for _, source := range p.Sources {
		family := "ip"
		if source.Addr().Is6() && !source.Addr().Is4In6() {
			family = "ip6"
		}
		fmt.Fprintf(&b, "\t\t%s saddr %s meta mark set %d\n", family, source, p.Mark)
	}
	b.WriteString("\t}\n\n")

	b.WriteString("\tchain killswitch {\n")
	b.WriteString("\t\ttype filter hook forward priority -100; policy accept;\n")
	for _, source := range p.Sources {
		family := "ip"
		if source.Addr().Is6() && !source.Addr().Is4In6() {
			family = "ip6"
		}
		// Anything from a routed client that is not leaving through the
		// profile's interface is a leak, and is dropped rather than sent out
		// over the household's own line.
		fmt.Fprintf(&b, "\t\t%s saddr %s oifname != \"%s\" drop\n", family, source, p.Interface)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	b.WriteString("RULES\n")

	return b.String(), nil
}

// RenderTeardown removes what RenderPolicyRouting installed.
func RenderTeardown(p EgressProfile) string {
	var b strings.Builder

	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by SedDNS. Edits will be overwritten.\n\n")
	fmt.Fprintf(&b, "ip rule del fwmark %d table %d 2>/dev/null || true\n", p.Mark, p.Table)
	fmt.Fprintf(&b, "ip route flush table %d 2>/dev/null || true\n", p.Table)
	b.WriteString("nft delete table inet aegisdns_egress 2>/dev/null || true\n")

	return b.String()
}
