package continuity

import (
	"fmt"
	"net/netip"
	"strings"
)

// Data-plane failover is a virtual address, not a cleverer resolver.
//
// Clients are configured with one DNS server address, usually by DHCP, and
// changing that on every device is not a failover plan. So the pair shares an
// address: whichever node holds it answers, and the other takes it over within
// seconds if the first stops working. keepalived already implements VRRP
// properly, has been doing so for two decades, and is packaged everywhere —
// generating its configuration is a far better use of the effort than writing
// a second VRRP.

// VRRPConfig describes one virtual address.
type VRRPConfig struct {
	// Interface is the NIC the address lives on.
	Interface string

	// VirtualAddress is what clients are pointed at.
	VirtualAddress netip.Addr

	// RouterID identifies this VRRP group on the segment. Two unrelated pairs
	// sharing a number will fight over each other's addresses.
	RouterID int

	// Priority decides who holds the address when everyone is healthy.
	Priority int

	// Peers are the other nodes' real addresses. Unicast is used rather than
	// multicast because plenty of consumer switches and access points quietly
	// drop VRRP multicast.
	Peers []netip.Addr

	// SelfAddress is this node's real address.
	SelfAddress netip.Addr

	// Password authenticates VRRP adverts within the pair.
	Password string

	// CheckPort is the DNS port the health script queries.
	CheckPort int
}

// Validate reports what is missing or contradictory.
func (c VRRPConfig) Validate() error {
	var problems []string

	if c.Interface == "" {
		problems = append(problems, "an interface is required")
	}
	if !c.VirtualAddress.IsValid() {
		problems = append(problems, "a virtual address is required")
	}
	if c.RouterID < 1 || c.RouterID > 255 {
		problems = append(problems, "router id must be between 1 and 255")
	}
	if c.Priority < 1 || c.Priority > 254 {
		problems = append(problems, "priority must be between 1 and 254")
	}
	if len(c.Peers) == 0 {
		problems = append(problems, "at least one peer address is required")
	}
	if len(c.Password) > 8 {
		// VRRP's simple authentication truncates silently past eight bytes,
		// which would leave a pair that never agrees and no clue why.
		problems = append(problems, "password must be at most 8 characters (VRRP truncates longer ones)")
	}

	if len(problems) > 0 {
		return fmt.Errorf("virtual address configuration: %s", strings.Join(problems, "; "))
	}

	return nil
}

// RenderKeepalived produces a keepalived configuration.
//
// The health script is the important part. Tracking the process only proves
// something is running; a resolver can hold its socket open and stop answering,
// and the pair would keep the address on the node that has stopped working. So
// the script asks the node to resolve a name, and a failure lowers this node's
// priority enough for the other one to take over.
func RenderKeepalived(cfg VRRPConfig, checkScriptPath string) (string, error) {
	if err := cfg.Validate(); err != nil {
		return "", err
	}

	var b strings.Builder

	b.WriteString("# Generated by SedDNS. Edits will be overwritten.\n\n")

	b.WriteString("vrrp_script chk_aegisdns {\n")
	b.WriteString(fmt.Sprintf("    script \"%s\"\n", checkScriptPath))
	b.WriteString("    interval 2\n")
	b.WriteString("    timeout 3\n")
	// Two consecutive failures before acting, so one dropped packet on a busy
	// moment does not move the address.
	b.WriteString("    fall 2\n")
	b.WriteString("    rise 2\n")
	// The weight is larger than any sensible priority gap, so a failing node
	// always loses to a healthy one.
	b.WriteString("    weight -50\n")
	b.WriteString("}\n\n")

	state := "BACKUP"
	if cfg.Priority >= 150 {
		state = "MASTER"
	}

	b.WriteString("vrrp_instance aegisdns {\n")
	b.WriteString(fmt.Sprintf("    state %s\n", state))
	b.WriteString(fmt.Sprintf("    interface %s\n", cfg.Interface))
	b.WriteString(fmt.Sprintf("    virtual_router_id %d\n", cfg.RouterID))
	b.WriteString(fmt.Sprintf("    priority %d\n", cfg.Priority))
	b.WriteString("    advert_int 1\n")
	// Without this, the recovering original master snatches the address back
	// the moment it boots, interrupting service a second time for no gain.
	b.WriteString("    nopreempt\n")

	if cfg.Password != "" {
		b.WriteString("    authentication {\n")
		b.WriteString("        auth_type PASS\n")
		b.WriteString(fmt.Sprintf("        auth_pass %s\n", cfg.Password))
		b.WriteString("    }\n")
	}

	if cfg.SelfAddress.IsValid() {
		b.WriteString(fmt.Sprintf("    unicast_src_ip %s\n", cfg.SelfAddress))
	}
	b.WriteString("    unicast_peer {\n")
	for _, peer := range cfg.Peers {
		b.WriteString(fmt.Sprintf("        %s\n", peer))
	}
	b.WriteString("    }\n")

	b.WriteString("    virtual_ipaddress {\n")
	b.WriteString(fmt.Sprintf("        %s dev %s\n", cfg.VirtualAddress, cfg.Interface))
	b.WriteString("    }\n")

	b.WriteString("    track_script {\n")
	b.WriteString("        chk_aegisdns\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String(), nil
}

// RenderCheckScript produces the health script keepalived runs.
//
// It resolves a name through this node's own listener. Anything less — a port
// check, a process check — passes on a resolver that has stopped answering,
// which is the failure this whole arrangement exists to survive.
func RenderCheckScript(port int, probeName string) string {
	if port <= 0 {
		port = 53
	}
	if probeName == "" {
		// A name that always resolves and is cheap for the upstream. The
		// answer is irrelevant; only that one comes back at all.
		probeName = "id.server"
	}

	return fmt.Sprintf(`#!/bin/sh
# Generated by SedDNS. Edits will be overwritten.
#
# Exits non-zero when this node cannot answer a DNS query, which lowers its
# VRRP priority and hands the virtual address to the other node. Checking the
# process instead would keep the address on a resolver that is alive and mute.

exec dig @127.0.0.1 -p %d +short +time=1 +tries=1 %s CH TXT > /dev/null 2>&1
`, port, probeName)
}

// SysctlNote is what an operator has to set for a node to bind the virtual
// address before it owns it.
const SysctlNote = "net.ipv4.ip_nonlocal_bind=1"
